---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: ${name}
    namespace: ${namespace}
rules:
  - apiGroups:
       - ""
    resourceNames:
      %{~ for s in resourcenames ~}
      - ${s}
      %{~ endfor ~}
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: ${name}
    namespace: ${namespace}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: ${name}
subjects:
  - kind: ServiceAccount
    name: aws-alb-ingress-controller
    namespace: kube-system