apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: ${name}
    namespace: ${namespace}
rules:
  - apiGroups:
       - ""
    resourceNames:
      %{~ for s in resourcenames ~}
      - ${s}
      %{~ endfor ~}
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch