name: Scan

on: [push, pull_request]

permissions: read-all

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          skip_check: "CKV_AWS_356,CKV_AWS_111"
          quiet: true
          skip_path: "examples"